server:
  port: 8080

rest.client:
  cards.url: http://localhost:8081

logging:
  level:
    org:
      springframework:
        web: DEBUG

feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000
        loggerLevel: full